# Generated by Django 5.1.4 on 2025-01-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="game_identifier",
            field=models.CharField(
                default=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="players",
                    to="game.game",
                ),
                editable=False,
                max_length=16,
            ),
        ),
    ]
