# Generated by Django 5.1.4 on 2025-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_player_game_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="game_identifier",
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
