# Generated by Django 5.1.4 on 2025-01-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_player_game_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="id",
            new_name="game_id",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="id",
            new_name="player_id",
        ),
    ]
