# Generated by Django 5.1.4 on 2025-01-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_rename_id_game_game_id_rename_id_player_player_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="game_id",
            new_name="gameId",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="player_id",
            new_name="playerId",
        ),
    ]
