# Generated by Django 5.1.4 on 2025-01-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
    ]
