# Generated by Django 5.1.4 on 2025-01-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_first_name_remove_account_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_id",
            new_name="userId",
        ),
    ]
